title: Helios ☀️
description: High-efficiency, security-hardened Lodash alternative
theme: jekyll-theme-cayman
github:
  is_project_page: true
  repository_url: https://github.com/apithy-edson-gomez/helios
show_downloads: false
permalink: pretty
include:
  - .github
